### PR TITLE
Test PR for CI tools

### PR DESCRIPTION
**Pull request by MasonProtter**
Deleted some whitespace.

### CODE REVIEW

**Comment by MasonProtter** [comment]
@PerezHz Any idea why Appveyor isn't running?

**Comment by PerezHz** [comment]
@MasonProtter don't know for sure, but just tried to activate my fork in appveyor and it is now [running](https://ci.appveyor.com/project/PerezHz/symbolics-jl) correctly; did you go to the projects tab in appveyor and clicked on "+ new project" and added the original Symbolics.jl repo?

**Comment by PerezHz** [comment]
It looks like appveyor is now ready; could you please try to push another commit to trigger a build?

**Comment by MasonProtter** [comment]
Its saying that a build is queued in the checks tab but not in the merge box. Strange.

**Comment by PerezHz** [comment]
🤔... Could you please try to go to `https://ci.appveyor.com/project/MasonProtter/symbolics-jl` and see if there's a "new build" button which you can click?

**Pull request merged**
