### PR TITLE
Construct UpTuple/DownTuple as wrappers around Array instead of Tuple

### LINKED ISSUE #11: Handling of Up and Down tuples
Right now, we have an `UpTuple` and `DownTuple` type which are just wrappers around tuples. I think I'd prefer to do something array based and try to take advantage of all the great machinery that Julia provides for arrays, ie. adjoint and all that jazz.

Ideally, whatever system gets cooked up should be easily extended to work with differential geometry concepts because my real interest here, once I get through SICM, is to move onto Functional Differential Geometry using Symbolics.

### PR DESCRIPTION
**Pull request by PerezHz**
This PR is an attempt to fix #11. UpTuple and DownTuple are now wrappers around Vector (i.e., 1-dim Array), instead of Tuple, as is currently done. Tests seem to be passing, but I think it might be improved even more... is this kind of what you had in mind, @MasonProtter ?

### CODE REVIEW

**Comment by PerezHz** [comment]
Btw, I updated appveyor.yml, and this time I think the build was triggered correctly

**Comment by MasonProtter** [comment]
Looks good! Would you mind adding some more tests of the uptuples and downtuples?

**Comment by PerezHz** [comment]
> Looks good! Would you mind adding some more tests of the uptuples and downtuples?

Great! Just added some more tests for UpTuple/DownTuple; I noted that DownTuple was not exported so added it to exports

**Comment by PerezHz** [comment]
This is where codecov would prove itself useful... Have you checked the codecov app has adequate permissions on your GitHub account? I was thinking that perhaps we could also try to use coveralls and see if we have better luck with that

**Comment by MasonProtter** [comment]
Yeah it has full permissions, no idea why this is happening. Perhaps coveralls is a good idea

**Comment by PerezHz** [comment]
Thanks for merging!

**Pull request merged**
